#!/usr/bin/env perl
# BEGIN { $ENV{MOJO_MODE} = 'production'; }
use Mojolicious::Lite;

use FindBin '$RealBin';
use lib $RealBin;

app->secret('!bteam!');

get '/' => 'index';

group {
    under sub {
        require BTeam::RPC;
    };
    get '/rpc/pending'      => sub { BTeam::RPC->pending(@_)     };
    get '/rpc/in_progress'  => sub { BTeam::RPC->in_progress(@_) };
    get '/rpc/stalled'      => sub { BTeam::RPC->stalled(@_)     };
    get '/rpc/all'          => sub { BTeam::RPC->all(@_)         };
};

app->start;
__DATA__
@@ index.html.ep
<!DOCTYPE html>
<html>

<head>
  <title>bteam dashboard</title>
  <script src="http://yui.yahooapis.com/3.17.2/build/yui/yui-min.js"></script>
  <script src="moment.js"></script>
  <script src="dashboard.js"></script>
  <style>
    body {
      font-family: sans-serif;
      font-size: small;
      background: url(noise.png) #666;
    }
    .yui3-datatable-table {
      width: 100%;
      max-width: 1024px;
    }
    .yui3-datatable-message-content {
      background: #fff;
    }
    .table_title {
      color: #fff;
      font-style: normal;
      font-weight: bold;
      font-size: large;
      text-transform: uppercase;
    }
    .table_caption {
      color: #ddd;
      font-style: normal;
      font-weight: bold;
      font-size: small;
    }
    .id {
      text-align: right;
    }
    .summary {
      width: 100%;
    }
    .duration {
      white-space: nowrap;
      text-align: right;
    }
    #github {
      position: absolute;
      top: 10px;
      right: 10px;
    }
    #github a {
      color: #bbb;
    }
    #github a:hover {
      color: #fff;
    }
  </style>
</head>

<body class="yui3-skin-sam">
  <div id="pending"></div>
  <div id="in_progress"></div>
  <div id="stalled"></div>
  <div id="all"></div>
  <div id="github">
    <a href="https://github.com/globau/bteam-dashboard">source</a>
  </div>
</body>

</html>
